// @generated by sync-models on 2026-04-10T11:00:51.360Z — DO NOT EDIT
// To customize display metadata, edit libs/types/src/model-overrides.json
// Re-run: pnpm sync-models

export const PROVIDER_MODEL_MAP = {
  anthropic: [
    "claude-3-haiku-20240307",
    "claude-haiku-4-5-20251001",
    "claude-opus-4-1-20250805",
    "claude-opus-4-20250514",
    "claude-opus-4-5-20251101",
    "claude-opus-4-6",
    "claude-sonnet-4-20250514",
    "claude-sonnet-4-5-20250929",
    "claude-sonnet-4-6",
  ] as const,
  openai: [
    "codex-gpt-4",
    "codex-gpt-4-0613",
    "codex-gpt-4-turbo",
    "codex-gpt-4-turbo-2024-04-09",
    "codex-gpt-4.1",
    "codex-gpt-4.1-2025-04-14",
    "codex-gpt-4.1-mini",
    "codex-gpt-4.1-mini-2025-04-14",
    "codex-gpt-4.1-nano",
    "codex-gpt-4.1-nano-2025-04-14",
    "codex-gpt-4o",
    "codex-gpt-4o-2024-05-13",
    "codex-gpt-4o-2024-08-06",
    "codex-gpt-4o-2024-11-20",
    "codex-gpt-4o-audio-preview",
    "codex-gpt-4o-audio-preview-2024-12-17",
    "codex-gpt-4o-audio-preview-2025-06-03",
    "codex-gpt-4o-mini",
    "codex-gpt-4o-mini-2024-07-18",
    "codex-gpt-4o-mini-audio-preview",
    "codex-gpt-4o-mini-audio-preview-2024-12-17",
    "codex-gpt-4o-mini-realtime-preview",
    "codex-gpt-4o-mini-realtime-preview-2024-12-17",
    "codex-gpt-4o-mini-search-preview",
    "codex-gpt-4o-mini-search-preview-2025-03-11",
    "codex-gpt-4o-mini-transcribe",
    "codex-gpt-4o-mini-transcribe-2025-03-20",
    "codex-gpt-4o-mini-transcribe-2025-12-15",
    "codex-gpt-4o-mini-tts",
    "codex-gpt-4o-mini-tts-2025-03-20",
    "codex-gpt-4o-mini-tts-2025-12-15",
    "codex-gpt-4o-realtime-preview",
    "codex-gpt-4o-realtime-preview-2024-12-17",
    "codex-gpt-4o-realtime-preview-2025-06-03",
    "codex-gpt-4o-search-preview",
    "codex-gpt-4o-search-preview-2025-03-11",
    "codex-gpt-4o-transcribe",
    "codex-gpt-4o-transcribe-diarize",
    "codex-gpt-5",
    "codex-gpt-5-2025-08-07",
    "codex-gpt-5-chat-latest",
    "codex-gpt-5-codex",
    "codex-gpt-5-mini",
    "codex-gpt-5-mini-2025-08-07",
    "codex-gpt-5-nano",
    "codex-gpt-5-nano-2025-08-07",
    "codex-gpt-5-pro",
    "codex-gpt-5-pro-2025-10-06",
    "codex-gpt-5-search-api",
    "codex-gpt-5-search-api-2025-10-14",
    "codex-gpt-5.1",
    "codex-gpt-5.1-2025-11-13",
    "codex-gpt-5.1-chat-latest",
    "codex-gpt-5.1-codex",
    "codex-gpt-5.1-codex-max",
    "codex-gpt-5.1-codex-mini",
    "codex-gpt-5.2",
    "codex-gpt-5.2-2025-12-11",
    "codex-gpt-5.2-chat-latest",
    "codex-gpt-5.2-codex",
    "codex-gpt-5.2-pro",
    "codex-gpt-5.2-pro-2025-12-11",
    "codex-gpt-5.3-chat-latest",
    "codex-gpt-5.3-codex",
    "codex-gpt-5.4",
    "codex-gpt-5.4-2026-03-05",
    "codex-gpt-5.4-mini",
    "codex-gpt-5.4-mini-2026-03-17",
    "codex-gpt-5.4-nano",
    "codex-gpt-5.4-nano-2026-03-17",
    "codex-gpt-5.4-pro",
    "codex-gpt-5.4-pro-2026-03-05",
    "codex-o1",
    "codex-o1-2024-12-17",
    "codex-o1-pro",
    "codex-o1-pro-2025-03-19",
    "codex-o3",
    "codex-o3-2025-04-16",
    "codex-o3-mini",
    "codex-o3-mini-2025-01-31",
    "codex-o4-mini",
    "codex-o4-mini-2025-04-16",
    "codex-o4-mini-deep-research",
    "codex-o4-mini-deep-research-2025-06-26",
  ] as const,
  copilot: [
    "copilot-ai21-labs/ai21-jamba-1.5-large",
    "copilot-cohere/cohere-command-a",
    "copilot-cohere/cohere-command-r-08-2024",
    "copilot-cohere/cohere-command-r-plus-08-2024",
    "copilot-deepseek/deepseek-r1",
    "copilot-deepseek/deepseek-r1-0528",
    "copilot-deepseek/deepseek-v3-0324",
    "copilot-meta/llama-3.2-11b-vision-instruct",
    "copilot-meta/llama-3.2-90b-vision-instruct",
    "copilot-meta/llama-3.3-70b-instruct",
    "copilot-meta/llama-4-maverick-17b-128e-instruct-fp8",
    "copilot-meta/llama-4-scout-17b-16e-instruct",
    "copilot-meta/meta-llama-3.1-405b-instruct",
    "copilot-meta/meta-llama-3.1-8b-instruct",
    "copilot-microsoft/mai-ds-r1",
    "copilot-microsoft/phi-4",
    "copilot-microsoft/phi-4-mini-instruct",
    "copilot-microsoft/phi-4-mini-reasoning",
    "copilot-microsoft/phi-4-multimodal-instruct",
    "copilot-microsoft/phi-4-reasoning",
    "copilot-mistral-ai/codestral-2501",
    "copilot-mistral-ai/ministral-3b",
    "copilot-mistral-ai/mistral-medium-2505",
    "copilot-mistral-ai/mistral-small-2503",
    "copilot-openai/gpt-4.1",
    "copilot-openai/gpt-4.1-mini",
    "copilot-openai/gpt-4.1-nano",
    "copilot-openai/gpt-4o",
    "copilot-openai/gpt-4o-mini",
    "copilot-openai/gpt-5",
    "copilot-openai/gpt-5-chat",
    "copilot-openai/gpt-5-mini",
    "copilot-openai/gpt-5-nano",
    "copilot-openai/o1",
    "copilot-openai/o1-mini",
    "copilot-openai/o1-preview",
    "copilot-openai/o3",
    "copilot-openai/o3-mini",
    "copilot-openai/o4-mini",
    "copilot-openai/text-embedding-3-large",
    "copilot-openai/text-embedding-3-small",
    "copilot-xai/grok-3",
    "copilot-xai/grok-3-mini",
  ] as const,
  cursor: [
    "cursor-composer-1",
    "cursor-composer-1.5",
    "cursor-composer-2",
    "cursor-gemini-2.5-flash",
    "cursor-gemini-3-flash",
    "cursor-gemini-3-pro",
    "cursor-gemini-3-pro-image-preview",
    "cursor-gemini-3.1-pro",
    "cursor-gpt-5",
    "cursor-gpt-5-codex",
    "cursor-gpt-5-fast",
    "cursor-gpt-5-mini",
    "cursor-gpt-5.1-codex",
    "cursor-gpt-5.1-codex-max",
    "cursor-gpt-5.1-codex-mini",
    "cursor-gpt-5.2",
    "cursor-gpt-5.2-codex",
    "cursor-gpt-5.3-codex",
    "cursor-gpt-5.4",
    "cursor-gpt-5.4-mini",
    "cursor-gpt-5.4-nano",
    "cursor-grok-4.20",
    "cursor-haiku-4.5",
    "cursor-kimi-k2.5",
    "cursor-opus-4.5",
    "cursor-opus-4.6",
    "cursor-opus-4.6-fast",
    "cursor-sonnet-4",
    "cursor-sonnet-4-1m",
    "cursor-sonnet-4.5",
    "cursor-sonnet-4.6",
  ] as const,
  google: [
    "gemini-2.0-flash",
    "gemini-2.0-flash-001",
    "gemini-2.0-flash-lite",
    "gemini-2.0-flash-lite-001",
    "gemini-2.5-computer-use-preview-10-2025",
    "gemini-2.5-flash",
    "gemini-2.5-flash-image",
    "gemini-2.5-flash-lite",
    "gemini-2.5-flash-native-audio-latest",
    "gemini-2.5-flash-native-audio-preview-09-2025",
    "gemini-2.5-flash-native-audio-preview-12-2025",
    "gemini-2.5-flash-preview-tts",
    "gemini-2.5-pro",
    "gemini-2.5-pro-preview-tts",
    "gemini-3-flash-preview",
    "gemini-3-pro-image-preview",
    "gemini-3-pro-preview",
    "gemini-3.1-flash-image-preview",
    "gemini-3.1-flash-lite-preview",
    "gemini-3.1-flash-live-preview",
    "gemini-3.1-pro-preview",
    "gemini-3.1-pro-preview-customtools",
    "gemini-embedding-001",
    "gemini-embedding-2-preview",
    "gemini-flash-latest",
    "gemini-flash-lite-latest",
    "gemini-pro-latest",
    "gemini-robotics-er-1.5-preview",
  ] as const,
} as const;

export type AnthropicModelId =
  | "claude-3-haiku-20240307"
  | "claude-haiku-4-5-20251001"
  | "claude-opus-4-1-20250805"
  | "claude-opus-4-20250514"
  | "claude-opus-4-5-20251101"
  | "claude-opus-4-6"
  | "claude-sonnet-4-20250514"
  | "claude-sonnet-4-5-20250929"
  | "claude-sonnet-4-6";

export type OpenaiModelId =
  | "codex-gpt-4"
  | "codex-gpt-4-0613"
  | "codex-gpt-4-turbo"
  | "codex-gpt-4-turbo-2024-04-09"
  | "codex-gpt-4.1"
  | "codex-gpt-4.1-2025-04-14"
  | "codex-gpt-4.1-mini"
  | "codex-gpt-4.1-mini-2025-04-14"
  | "codex-gpt-4.1-nano"
  | "codex-gpt-4.1-nano-2025-04-14"
  | "codex-gpt-4o"
  | "codex-gpt-4o-2024-05-13"
  | "codex-gpt-4o-2024-08-06"
  | "codex-gpt-4o-2024-11-20"
  | "codex-gpt-4o-audio-preview"
  | "codex-gpt-4o-audio-preview-2024-12-17"
  | "codex-gpt-4o-audio-preview-2025-06-03"
  | "codex-gpt-4o-mini"
  | "codex-gpt-4o-mini-2024-07-18"
  | "codex-gpt-4o-mini-audio-preview"
  | "codex-gpt-4o-mini-audio-preview-2024-12-17"
  | "codex-gpt-4o-mini-realtime-preview"
  | "codex-gpt-4o-mini-realtime-preview-2024-12-17"
  | "codex-gpt-4o-mini-search-preview"
  | "codex-gpt-4o-mini-search-preview-2025-03-11"
  | "codex-gpt-4o-mini-transcribe"
  | "codex-gpt-4o-mini-transcribe-2025-03-20"
  | "codex-gpt-4o-mini-transcribe-2025-12-15"
  | "codex-gpt-4o-mini-tts"
  | "codex-gpt-4o-mini-tts-2025-03-20"
  | "codex-gpt-4o-mini-tts-2025-12-15"
  | "codex-gpt-4o-realtime-preview"
  | "codex-gpt-4o-realtime-preview-2024-12-17"
  | "codex-gpt-4o-realtime-preview-2025-06-03"
  | "codex-gpt-4o-search-preview"
  | "codex-gpt-4o-search-preview-2025-03-11"
  | "codex-gpt-4o-transcribe"
  | "codex-gpt-4o-transcribe-diarize"
  | "codex-gpt-5"
  | "codex-gpt-5-2025-08-07"
  | "codex-gpt-5-chat-latest"
  | "codex-gpt-5-codex"
  | "codex-gpt-5-mini"
  | "codex-gpt-5-mini-2025-08-07"
  | "codex-gpt-5-nano"
  | "codex-gpt-5-nano-2025-08-07"
  | "codex-gpt-5-pro"
  | "codex-gpt-5-pro-2025-10-06"
  | "codex-gpt-5-search-api"
  | "codex-gpt-5-search-api-2025-10-14"
  | "codex-gpt-5.1"
  | "codex-gpt-5.1-2025-11-13"
  | "codex-gpt-5.1-chat-latest"
  | "codex-gpt-5.1-codex"
  | "codex-gpt-5.1-codex-max"
  | "codex-gpt-5.1-codex-mini"
  | "codex-gpt-5.2"
  | "codex-gpt-5.2-2025-12-11"
  | "codex-gpt-5.2-chat-latest"
  | "codex-gpt-5.2-codex"
  | "codex-gpt-5.2-pro"
  | "codex-gpt-5.2-pro-2025-12-11"
  | "codex-gpt-5.3-chat-latest"
  | "codex-gpt-5.3-codex"
  | "codex-gpt-5.4"
  | "codex-gpt-5.4-2026-03-05"
  | "codex-gpt-5.4-mini"
  | "codex-gpt-5.4-mini-2026-03-17"
  | "codex-gpt-5.4-nano"
  | "codex-gpt-5.4-nano-2026-03-17"
  | "codex-gpt-5.4-pro"
  | "codex-gpt-5.4-pro-2026-03-05"
  | "codex-o1"
  | "codex-o1-2024-12-17"
  | "codex-o1-pro"
  | "codex-o1-pro-2025-03-19"
  | "codex-o3"
  | "codex-o3-2025-04-16"
  | "codex-o3-mini"
  | "codex-o3-mini-2025-01-31"
  | "codex-o4-mini"
  | "codex-o4-mini-2025-04-16"
  | "codex-o4-mini-deep-research"
  | "codex-o4-mini-deep-research-2025-06-26";

export type CopilotModelId =
  | "copilot-ai21-labs/ai21-jamba-1.5-large"
  | "copilot-cohere/cohere-command-a"
  | "copilot-cohere/cohere-command-r-08-2024"
  | "copilot-cohere/cohere-command-r-plus-08-2024"
  | "copilot-deepseek/deepseek-r1"
  | "copilot-deepseek/deepseek-r1-0528"
  | "copilot-deepseek/deepseek-v3-0324"
  | "copilot-meta/llama-3.2-11b-vision-instruct"
  | "copilot-meta/llama-3.2-90b-vision-instruct"
  | "copilot-meta/llama-3.3-70b-instruct"
  | "copilot-meta/llama-4-maverick-17b-128e-instruct-fp8"
  | "copilot-meta/llama-4-scout-17b-16e-instruct"
  | "copilot-meta/meta-llama-3.1-405b-instruct"
  | "copilot-meta/meta-llama-3.1-8b-instruct"
  | "copilot-microsoft/mai-ds-r1"
  | "copilot-microsoft/phi-4"
  | "copilot-microsoft/phi-4-mini-instruct"
  | "copilot-microsoft/phi-4-mini-reasoning"
  | "copilot-microsoft/phi-4-multimodal-instruct"
  | "copilot-microsoft/phi-4-reasoning"
  | "copilot-mistral-ai/codestral-2501"
  | "copilot-mistral-ai/ministral-3b"
  | "copilot-mistral-ai/mistral-medium-2505"
  | "copilot-mistral-ai/mistral-small-2503"
  | "copilot-openai/gpt-4.1"
  | "copilot-openai/gpt-4.1-mini"
  | "copilot-openai/gpt-4.1-nano"
  | "copilot-openai/gpt-4o"
  | "copilot-openai/gpt-4o-mini"
  | "copilot-openai/gpt-5"
  | "copilot-openai/gpt-5-chat"
  | "copilot-openai/gpt-5-mini"
  | "copilot-openai/gpt-5-nano"
  | "copilot-openai/o1"
  | "copilot-openai/o1-mini"
  | "copilot-openai/o1-preview"
  | "copilot-openai/o3"
  | "copilot-openai/o3-mini"
  | "copilot-openai/o4-mini"
  | "copilot-openai/text-embedding-3-large"
  | "copilot-openai/text-embedding-3-small"
  | "copilot-xai/grok-3"
  | "copilot-xai/grok-3-mini";

export type CursorModelId =
  | "cursor-composer-1"
  | "cursor-composer-1.5"
  | "cursor-composer-2"
  | "cursor-gemini-2.5-flash"
  | "cursor-gemini-3-flash"
  | "cursor-gemini-3-pro"
  | "cursor-gemini-3-pro-image-preview"
  | "cursor-gemini-3.1-pro"
  | "cursor-gpt-5"
  | "cursor-gpt-5-codex"
  | "cursor-gpt-5-fast"
  | "cursor-gpt-5-mini"
  | "cursor-gpt-5.1-codex"
  | "cursor-gpt-5.1-codex-max"
  | "cursor-gpt-5.1-codex-mini"
  | "cursor-gpt-5.2"
  | "cursor-gpt-5.2-codex"
  | "cursor-gpt-5.3-codex"
  | "cursor-gpt-5.4"
  | "cursor-gpt-5.4-mini"
  | "cursor-gpt-5.4-nano"
  | "cursor-grok-4.20"
  | "cursor-haiku-4.5"
  | "cursor-kimi-k2.5"
  | "cursor-opus-4.5"
  | "cursor-opus-4.6"
  | "cursor-opus-4.6-fast"
  | "cursor-sonnet-4"
  | "cursor-sonnet-4-1m"
  | "cursor-sonnet-4.5"
  | "cursor-sonnet-4.6";

export type GoogleModelId =
  | "gemini-2.0-flash"
  | "gemini-2.0-flash-001"
  | "gemini-2.0-flash-lite"
  | "gemini-2.0-flash-lite-001"
  | "gemini-2.5-computer-use-preview-10-2025"
  | "gemini-2.5-flash"
  | "gemini-2.5-flash-image"
  | "gemini-2.5-flash-lite"
  | "gemini-2.5-flash-native-audio-latest"
  | "gemini-2.5-flash-native-audio-preview-09-2025"
  | "gemini-2.5-flash-native-audio-preview-12-2025"
  | "gemini-2.5-flash-preview-tts"
  | "gemini-2.5-pro"
  | "gemini-2.5-pro-preview-tts"
  | "gemini-3-flash-preview"
  | "gemini-3-pro-image-preview"
  | "gemini-3-pro-preview"
  | "gemini-3.1-flash-image-preview"
  | "gemini-3.1-flash-lite-preview"
  | "gemini-3.1-flash-live-preview"
  | "gemini-3.1-pro-preview"
  | "gemini-3.1-pro-preview-customtools"
  | "gemini-embedding-001"
  | "gemini-embedding-2-preview"
  | "gemini-flash-latest"
  | "gemini-flash-lite-latest"
  | "gemini-pro-latest"
  | "gemini-robotics-er-1.5-preview";

export type ModelId =
  | AnthropicModelId
  | OpenaiModelId
  | CopilotModelId
  | CursorModelId
  | GoogleModelId;

export const MODEL_ALIASES: Record<string, string> = {
  "claude-haiku": "claude-haiku-4-5-20251001",
  haiku: "claude-haiku-4-5-20251001",
  "claude-opus": "claude-opus-4-6",
  opus: "claude-opus-4-6",
  "claude-sonnet": "claude-sonnet-4-6",
  sonnet: "claude-sonnet-4-6",
};

export const PROVIDER_FOR_MODEL: Record<string, string> = {
  "claude-3-haiku-20240307": "anthropic",
  "claude-haiku-4-5-20251001": "anthropic",
  "claude-opus-4-1-20250805": "anthropic",
  "claude-opus-4-20250514": "anthropic",
  "claude-opus-4-5-20251101": "anthropic",
  "claude-opus-4-6": "anthropic",
  "claude-sonnet-4-20250514": "anthropic",
  "claude-sonnet-4-5-20250929": "anthropic",
  "claude-sonnet-4-6": "anthropic",
  "codex-gpt-4": "openai",
  "codex-gpt-4-0613": "openai",
  "codex-gpt-4-turbo": "openai",
  "codex-gpt-4-turbo-2024-04-09": "openai",
  "codex-gpt-4.1": "openai",
  "codex-gpt-4.1-2025-04-14": "openai",
  "codex-gpt-4.1-mini": "openai",
  "codex-gpt-4.1-mini-2025-04-14": "openai",
  "codex-gpt-4.1-nano": "openai",
  "codex-gpt-4.1-nano-2025-04-14": "openai",
  "codex-gpt-4o": "openai",
  "codex-gpt-4o-2024-05-13": "openai",
  "codex-gpt-4o-2024-08-06": "openai",
  "codex-gpt-4o-2024-11-20": "openai",
  "codex-gpt-4o-audio-preview": "openai",
  "codex-gpt-4o-audio-preview-2024-12-17": "openai",
  "codex-gpt-4o-audio-preview-2025-06-03": "openai",
  "codex-gpt-4o-mini": "openai",
  "codex-gpt-4o-mini-2024-07-18": "openai",
  "codex-gpt-4o-mini-audio-preview": "openai",
  "codex-gpt-4o-mini-audio-preview-2024-12-17": "openai",
  "codex-gpt-4o-mini-realtime-preview": "openai",
  "codex-gpt-4o-mini-realtime-preview-2024-12-17": "openai",
  "codex-gpt-4o-mini-search-preview": "openai",
  "codex-gpt-4o-mini-search-preview-2025-03-11": "openai",
  "codex-gpt-4o-mini-transcribe": "openai",
  "codex-gpt-4o-mini-transcribe-2025-03-20": "openai",
  "codex-gpt-4o-mini-transcribe-2025-12-15": "openai",
  "codex-gpt-4o-mini-tts": "openai",
  "codex-gpt-4o-mini-tts-2025-03-20": "openai",
  "codex-gpt-4o-mini-tts-2025-12-15": "openai",
  "codex-gpt-4o-realtime-preview": "openai",
  "codex-gpt-4o-realtime-preview-2024-12-17": "openai",
  "codex-gpt-4o-realtime-preview-2025-06-03": "openai",
  "codex-gpt-4o-search-preview": "openai",
  "codex-gpt-4o-search-preview-2025-03-11": "openai",
  "codex-gpt-4o-transcribe": "openai",
  "codex-gpt-4o-transcribe-diarize": "openai",
  "codex-gpt-5": "openai",
  "codex-gpt-5-2025-08-07": "openai",
  "codex-gpt-5-chat-latest": "openai",
  "codex-gpt-5-codex": "openai",
  "codex-gpt-5-mini": "openai",
  "codex-gpt-5-mini-2025-08-07": "openai",
  "codex-gpt-5-nano": "openai",
  "codex-gpt-5-nano-2025-08-07": "openai",
  "codex-gpt-5-pro": "openai",
  "codex-gpt-5-pro-2025-10-06": "openai",
  "codex-gpt-5-search-api": "openai",
  "codex-gpt-5-search-api-2025-10-14": "openai",
  "codex-gpt-5.1": "openai",
  "codex-gpt-5.1-2025-11-13": "openai",
  "codex-gpt-5.1-chat-latest": "openai",
  "codex-gpt-5.1-codex": "openai",
  "codex-gpt-5.1-codex-max": "openai",
  "codex-gpt-5.1-codex-mini": "openai",
  "codex-gpt-5.2": "openai",
  "codex-gpt-5.2-2025-12-11": "openai",
  "codex-gpt-5.2-chat-latest": "openai",
  "codex-gpt-5.2-codex": "openai",
  "codex-gpt-5.2-pro": "openai",
  "codex-gpt-5.2-pro-2025-12-11": "openai",
  "codex-gpt-5.3-chat-latest": "openai",
  "codex-gpt-5.3-codex": "openai",
  "codex-gpt-5.4": "openai",
  "codex-gpt-5.4-2026-03-05": "openai",
  "codex-gpt-5.4-mini": "openai",
  "codex-gpt-5.4-mini-2026-03-17": "openai",
  "codex-gpt-5.4-nano": "openai",
  "codex-gpt-5.4-nano-2026-03-17": "openai",
  "codex-gpt-5.4-pro": "openai",
  "codex-gpt-5.4-pro-2026-03-05": "openai",
  "codex-o1": "openai",
  "codex-o1-2024-12-17": "openai",
  "codex-o1-pro": "openai",
  "codex-o1-pro-2025-03-19": "openai",
  "codex-o3": "openai",
  "codex-o3-2025-04-16": "openai",
  "codex-o3-mini": "openai",
  "codex-o3-mini-2025-01-31": "openai",
  "codex-o4-mini": "openai",
  "codex-o4-mini-2025-04-16": "openai",
  "codex-o4-mini-deep-research": "openai",
  "codex-o4-mini-deep-research-2025-06-26": "openai",
  "copilot-ai21-labs/ai21-jamba-1.5-large": "copilot",
  "copilot-cohere/cohere-command-a": "copilot",
  "copilot-cohere/cohere-command-r-08-2024": "copilot",
  "copilot-cohere/cohere-command-r-plus-08-2024": "copilot",
  "copilot-deepseek/deepseek-r1": "copilot",
  "copilot-deepseek/deepseek-r1-0528": "copilot",
  "copilot-deepseek/deepseek-v3-0324": "copilot",
  "copilot-meta/llama-3.2-11b-vision-instruct": "copilot",
  "copilot-meta/llama-3.2-90b-vision-instruct": "copilot",
  "copilot-meta/llama-3.3-70b-instruct": "copilot",
  "copilot-meta/llama-4-maverick-17b-128e-instruct-fp8": "copilot",
  "copilot-meta/llama-4-scout-17b-16e-instruct": "copilot",
  "copilot-meta/meta-llama-3.1-405b-instruct": "copilot",
  "copilot-meta/meta-llama-3.1-8b-instruct": "copilot",
  "copilot-microsoft/mai-ds-r1": "copilot",
  "copilot-microsoft/phi-4": "copilot",
  "copilot-microsoft/phi-4-mini-instruct": "copilot",
  "copilot-microsoft/phi-4-mini-reasoning": "copilot",
  "copilot-microsoft/phi-4-multimodal-instruct": "copilot",
  "copilot-microsoft/phi-4-reasoning": "copilot",
  "copilot-mistral-ai/codestral-2501": "copilot",
  "copilot-mistral-ai/ministral-3b": "copilot",
  "copilot-mistral-ai/mistral-medium-2505": "copilot",
  "copilot-mistral-ai/mistral-small-2503": "copilot",
  "copilot-openai/gpt-4.1": "copilot",
  "copilot-openai/gpt-4.1-mini": "copilot",
  "copilot-openai/gpt-4.1-nano": "copilot",
  "copilot-openai/gpt-4o": "copilot",
  "copilot-openai/gpt-4o-mini": "copilot",
  "copilot-openai/gpt-5": "copilot",
  "copilot-openai/gpt-5-chat": "copilot",
  "copilot-openai/gpt-5-mini": "copilot",
  "copilot-openai/gpt-5-nano": "copilot",
  "copilot-openai/o1": "copilot",
  "copilot-openai/o1-mini": "copilot",
  "copilot-openai/o1-preview": "copilot",
  "copilot-openai/o3": "copilot",
  "copilot-openai/o3-mini": "copilot",
  "copilot-openai/o4-mini": "copilot",
  "copilot-openai/text-embedding-3-large": "copilot",
  "copilot-openai/text-embedding-3-small": "copilot",
  "copilot-xai/grok-3": "copilot",
  "copilot-xai/grok-3-mini": "copilot",
  "cursor-composer-1": "cursor",
  "cursor-composer-1.5": "cursor",
  "cursor-composer-2": "cursor",
  "cursor-gemini-2.5-flash": "cursor",
  "cursor-gemini-3-flash": "cursor",
  "cursor-gemini-3-pro": "cursor",
  "cursor-gemini-3-pro-image-preview": "cursor",
  "cursor-gemini-3.1-pro": "cursor",
  "cursor-gpt-5": "cursor",
  "cursor-gpt-5-codex": "cursor",
  "cursor-gpt-5-fast": "cursor",
  "cursor-gpt-5-mini": "cursor",
  "cursor-gpt-5.1-codex": "cursor",
  "cursor-gpt-5.1-codex-max": "cursor",
  "cursor-gpt-5.1-codex-mini": "cursor",
  "cursor-gpt-5.2": "cursor",
  "cursor-gpt-5.2-codex": "cursor",
  "cursor-gpt-5.3-codex": "cursor",
  "cursor-gpt-5.4": "cursor",
  "cursor-gpt-5.4-mini": "cursor",
  "cursor-gpt-5.4-nano": "cursor",
  "cursor-grok-4.20": "cursor",
  "cursor-haiku-4.5": "cursor",
  "cursor-kimi-k2.5": "cursor",
  "cursor-opus-4.5": "cursor",
  "cursor-opus-4.6": "cursor",
  "cursor-opus-4.6-fast": "cursor",
  "cursor-sonnet-4": "cursor",
  "cursor-sonnet-4-1m": "cursor",
  "cursor-sonnet-4.5": "cursor",
  "cursor-sonnet-4.6": "cursor",
  "gemini-2.0-flash": "google",
  "gemini-2.0-flash-001": "google",
  "gemini-2.0-flash-lite": "google",
  "gemini-2.0-flash-lite-001": "google",
  "gemini-2.5-computer-use-preview-10-2025": "google",
  "gemini-2.5-flash": "google",
  "gemini-2.5-flash-image": "google",
  "gemini-2.5-flash-lite": "google",
  "gemini-2.5-flash-native-audio-latest": "google",
  "gemini-2.5-flash-native-audio-preview-09-2025": "google",
  "gemini-2.5-flash-native-audio-preview-12-2025": "google",
  "gemini-2.5-flash-preview-tts": "google",
  "gemini-2.5-pro": "google",
  "gemini-2.5-pro-preview-tts": "google",
  "gemini-3-flash-preview": "google",
  "gemini-3-pro-image-preview": "google",
  "gemini-3-pro-preview": "google",
  "gemini-3.1-flash-image-preview": "google",
  "gemini-3.1-flash-lite-preview": "google",
  "gemini-3.1-flash-live-preview": "google",
  "gemini-3.1-pro-preview": "google",
  "gemini-3.1-pro-preview-customtools": "google",
  "gemini-embedding-001": "google",
  "gemini-embedding-2-preview": "google",
  "gemini-flash-latest": "google",
  "gemini-flash-lite-latest": "google",
  "gemini-pro-latest": "google",
  "gemini-robotics-er-1.5-preview": "google",
};

export const DEFAULT_MODELS_REGISTRY: Record<string, string> = {
  claude: "claude-opus-4-6",
  codex: "codex-gpt-5.3-codex",
  google: "gemini-2.5-flash",
};
