// @generated by sync-models on 2026-04-09T12:00:00.000Z — DO NOT EDIT
// To customize display metadata, edit libs/types/src/model-overrides.json
// Re-run: pnpm sync-models

export const PROVIDER_MODEL_MAP = {
  anthropic: [
    'claude-haiku-4-5-20251001',
    'claude-sonnet-4-6',
    'claude-opus-4-6',
  ] as const,
  openai: [
    'codex-gpt-5.3-codex',
    'codex-gpt-5.3-codex-spark',
    'codex-gpt-5.2-codex',
    'codex-gpt-5.1-codex-max',
    'codex-gpt-5.1-codex-mini',
    'codex-gpt-5.1-codex',
    'codex-gpt-5-codex',
    'codex-gpt-5-codex-mini',
    'codex-gpt-5.2',
    'codex-gpt-5.1',
    'codex-gpt-5',
  ] as const,
  google: [
    'gemini-3-pro-preview',
    'gemini-3-flash-preview',
    'gemini-2.5-pro',
    'gemini-2.5-flash',
    'gemini-2.5-flash-lite',
  ] as const,
  copilot: [
    'copilot-claude-sonnet-4.6',
    'copilot-claude-sonnet-4.5',
    'copilot-claude-haiku-4.5',
    'copilot-claude-opus-4.5',
    'copilot-claude-sonnet-4',
    'copilot-gpt-5.2-codex',
    'copilot-gpt-5.1-codex-max',
    'copilot-gpt-5.1-codex',
    'copilot-gpt-5.2',
    'copilot-gpt-5.1',
    'copilot-gpt-5',
    'copilot-gpt-5.1-codex-mini',
    'copilot-gpt-5-mini',
    'copilot-gpt-4.1',
    'copilot-gemini-3-pro-preview',
  ] as const,
  cursor: [
    'cursor-auto',
    'cursor-composer-1',
    'cursor-sonnet-4.6',
    'cursor-sonnet-4.6-thinking',
    'cursor-sonnet-4.5',
    'cursor-sonnet-4.5-thinking',
    'cursor-opus-4.5',
    'cursor-opus-4.5-thinking',
    'cursor-opus-4.1',
    'cursor-gemini-3-pro',
    'cursor-gemini-3-flash',
    'cursor-gpt-5.2',
    'cursor-gpt-5.1',
    'cursor-gpt-5.2-high',
    'cursor-gpt-5.1-high',
    'cursor-gpt-5.1-codex',
    'cursor-gpt-5.1-codex-high',
    'cursor-gpt-5.1-codex-max',
    'cursor-gpt-5.1-codex-max-high',
    'cursor-gpt-5.2-codex',
    'cursor-gpt-5.2-codex-high',
    'cursor-gpt-5.2-codex-max',
    'cursor-gpt-5.2-codex-max-high',
    'cursor-grok',
  ] as const,
  opencode: [
    'opencode-big-pickle',
    'opencode-glm-5-free',
    'opencode-gpt-5-nano',
    'opencode-kimi-k2.5-free',
    'opencode-minimax-m2.5-free',
  ] as const,
} as const;

export type AnthropicModelId = (typeof PROVIDER_MODEL_MAP.anthropic)[number];
export type OpenaiModelId = (typeof PROVIDER_MODEL_MAP.openai)[number];
export type GoogleModelId = (typeof PROVIDER_MODEL_MAP.google)[number];
export type CopilotRegistryModelId = (typeof PROVIDER_MODEL_MAP.copilot)[number];
export type CursorRegistryModelId = (typeof PROVIDER_MODEL_MAP.cursor)[number];
export type OpencodeRegistryModelId = (typeof PROVIDER_MODEL_MAP.opencode)[number];

export type RegistryModelId =
  | AnthropicModelId
  | OpenaiModelId
  | GoogleModelId
  | CopilotRegistryModelId
  | CursorRegistryModelId
  | OpencodeRegistryModelId;

export const MODEL_ALIASES: Record<string, string> = {
  'claude-haiku': 'claude-haiku-4-5-20251001',
  haiku: 'claude-haiku-4-5-20251001',
  'claude-sonnet': 'claude-sonnet-4-6',
  sonnet: 'claude-sonnet-4-6',
  'claude-opus': 'claude-opus-4-6',
  opus: 'claude-opus-4-6',
};

export const PROVIDER_FOR_MODEL: Record<string, string> = {
  'claude-haiku-4-5-20251001': 'anthropic',
  'claude-sonnet-4-6': 'anthropic',
  'claude-opus-4-6': 'anthropic',
  'codex-gpt-5.3-codex': 'openai',
  'codex-gpt-5.3-codex-spark': 'openai',
  'codex-gpt-5.2-codex': 'openai',
  'codex-gpt-5.1-codex-max': 'openai',
  'codex-gpt-5.1-codex-mini': 'openai',
  'codex-gpt-5.1-codex': 'openai',
  'codex-gpt-5-codex': 'openai',
  'codex-gpt-5-codex-mini': 'openai',
  'codex-gpt-5.2': 'openai',
  'codex-gpt-5.1': 'openai',
  'codex-gpt-5': 'openai',
  'gemini-3-pro-preview': 'google',
  'gemini-3-flash-preview': 'google',
  'gemini-2.5-pro': 'google',
  'gemini-2.5-flash': 'google',
  'gemini-2.5-flash-lite': 'google',
  'copilot-claude-sonnet-4.6': 'copilot',
  'copilot-claude-sonnet-4.5': 'copilot',
  'copilot-claude-haiku-4.5': 'copilot',
  'copilot-claude-opus-4.5': 'copilot',
  'copilot-claude-sonnet-4': 'copilot',
  'copilot-gpt-5.2-codex': 'copilot',
  'copilot-gpt-5.1-codex-max': 'copilot',
  'copilot-gpt-5.1-codex': 'copilot',
  'copilot-gpt-5.2': 'copilot',
  'copilot-gpt-5.1': 'copilot',
  'copilot-gpt-5': 'copilot',
  'copilot-gpt-5.1-codex-mini': 'copilot',
  'copilot-gpt-5-mini': 'copilot',
  'copilot-gpt-4.1': 'copilot',
  'copilot-gemini-3-pro-preview': 'copilot',
  'cursor-auto': 'cursor',
  'cursor-composer-1': 'cursor',
  'cursor-sonnet-4.6': 'cursor',
  'cursor-sonnet-4.6-thinking': 'cursor',
  'cursor-sonnet-4.5': 'cursor',
  'cursor-sonnet-4.5-thinking': 'cursor',
  'cursor-opus-4.5': 'cursor',
  'cursor-opus-4.5-thinking': 'cursor',
  'cursor-opus-4.1': 'cursor',
  'cursor-gemini-3-pro': 'cursor',
  'cursor-gemini-3-flash': 'cursor',
  'cursor-gpt-5.2': 'cursor',
  'cursor-gpt-5.1': 'cursor',
  'cursor-gpt-5.2-high': 'cursor',
  'cursor-gpt-5.1-high': 'cursor',
  'cursor-gpt-5.1-codex': 'cursor',
  'cursor-gpt-5.1-codex-high': 'cursor',
  'cursor-gpt-5.1-codex-max': 'cursor',
  'cursor-gpt-5.1-codex-max-high': 'cursor',
  'cursor-gpt-5.2-codex': 'cursor',
  'cursor-gpt-5.2-codex-high': 'cursor',
  'cursor-gpt-5.2-codex-max': 'cursor',
  'cursor-gpt-5.2-codex-max-high': 'cursor',
  'cursor-grok': 'cursor',
  'opencode-big-pickle': 'opencode',
  'opencode-glm-5-free': 'opencode',
  'opencode-gpt-5-nano': 'opencode',
  'opencode-kimi-k2.5-free': 'opencode',
  'opencode-minimax-m2.5-free': 'opencode',
};

export const DEFAULT_MODELS_REGISTRY: Record<string, string> = {
  claude: 'claude-opus-4-6',
  codex: 'codex-gpt-5.3-codex',
  google: 'gemini-2.5-flash',
  copilot: 'copilot-claude-sonnet-4.6',
  cursor: 'cursor-auto',
};
