"""Pegasus prompt templates -- centralized runtime prompt strings."""

MERGE_CONFLICT_RESOLUTION = (
    "This git repository has merge conflicts after squash-merging "
    "a feature branch into the target branch.\n\n"
    "Task description: {description}\n"
    "Feature branch: {branch}\n\n"
    "{context}\n\n"
    "## Instructions\n\n"
    "1. Run `git diff --name-only --diff-filter=U` to list all "
    "conflicting files.\n"
    "2. For each conflicting file, read the file and find all "
    "conflict markers (<<<<<<< / ======= / >>>>>>>).\n"
    "3. Resolve each conflict by keeping changes from BOTH sides "
    "where they are additive (new functions, new fields, new imports). "
    "When both sides modified the same lines, integrate the changes "
    "so both features work together.\n"
    "4. After resolving all conflicts in a file, run "
    "`git add <file>` to stage it.\n"
    "5. After all files are resolved, verify there are no remaining "
    "conflict markers by searching for '<<<<<<' across the codebase.\n"
    "6. Run any available test commands to verify the merge is correct.\n\n"
    "Do NOT commit \u2014 just resolve conflicts and stage files."
)
