/**
 * Snapshot tests for generated TypeScript content (FR-002)
 *
 * These tests ensure the codegen output matches expected structure.
 * Failing snapshots indicate a breaking change in the generator.
 * To update snapshots: vitest --update-snapshots
 */

import { describe, it, expect } from 'vitest';
import {
  buildRegistryContent,
  buildCapabilitiesContent,
  buildDisplayContent,
  buildProviderMap,
} from '../engine.js';
import type { ModelEntry } from '../types.js';

const FIXED_TIMESTAMP = '2026-04-09T12:00:00.000Z';

const FIXTURE_MODELS: ModelEntry[] = [
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    provider: 'anthropic',
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    reasoningCapable: false,
    stabilityTier: 'ga',
    contextWindow: 200000,
    aliases: ['claude-sonnet', 'sonnet'],
    defaultFor: 'claude',
  },
  {
    id: 'codex-gpt-5-codex',
    name: 'GPT-5-Codex',
    provider: 'openai',
    supportsVision: true,
    supportsTools: true,
    reasoningCapable: true,
    stabilityTier: 'ga',
    defaultFor: 'codex',
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'google',
    supportsVision: true,
    supportsTools: true,
    supportsThinking: true,
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    stabilityTier: 'ga',
  },
];

const FIXTURE_PROVIDER_MAP = buildProviderMap(FIXTURE_MODELS);

// ---------------------------------------------------------------------------
// buildRegistryContent — model-registry.gen.ts
// ---------------------------------------------------------------------------

describe('buildRegistryContent', () => {
  it('matches snapshot', () => {
    const content = buildRegistryContent(FIXTURE_MODELS, FIXTURE_PROVIDER_MAP, FIXED_TIMESTAMP);
    expect(content).toMatchSnapshot();
  });

  it('includes @generated header comment', () => {
    const content = buildRegistryContent(FIXTURE_MODELS, FIXTURE_PROVIDER_MAP, FIXED_TIMESTAMP);
    expect(content).toContain('// @generated by sync-models');
    expect(content).toContain('DO NOT EDIT');
  });

  it('exports PROVIDER_MODEL_MAP as const', () => {
    const content = buildRegistryContent(FIXTURE_MODELS, FIXTURE_PROVIDER_MAP, FIXED_TIMESTAMP);
    expect(content).toContain('export const PROVIDER_MODEL_MAP');
    expect(content).toContain('as const');
  });

  it('exports per-provider type unions', () => {
    const content = buildRegistryContent(FIXTURE_MODELS, FIXTURE_PROVIDER_MAP, FIXED_TIMESTAMP);
    expect(content).toContain('export type AnthropicModelId');
    expect(content).toContain('export type OpenaiModelId');
    expect(content).toContain('export type GoogleModelId');
  });

  it('exports MODEL_ALIASES with alias entries', () => {
    const content = buildRegistryContent(FIXTURE_MODELS, FIXTURE_PROVIDER_MAP, FIXED_TIMESTAMP);
    expect(content).toContain("export const MODEL_ALIASES");
    expect(content).toContain("'claude-sonnet': 'claude-sonnet-4-6'");
    expect(content).toContain("'sonnet': 'claude-sonnet-4-6'");
  });

  it('exports PROVIDER_FOR_MODEL with all models', () => {
    const content = buildRegistryContent(FIXTURE_MODELS, FIXTURE_PROVIDER_MAP, FIXED_TIMESTAMP);
    expect(content).toContain("export const PROVIDER_FOR_MODEL");
    expect(content).toContain("'claude-sonnet-4-6': 'anthropic'");
    expect(content).toContain("'codex-gpt-5-codex': 'openai'");
    expect(content).toContain("'gemini-2.5-flash': 'google'");
  });

  it('exports DEFAULT_MODELS_REGISTRY', () => {
    const content = buildRegistryContent(FIXTURE_MODELS, FIXTURE_PROVIDER_MAP, FIXED_TIMESTAMP);
    expect(content).toContain("export const DEFAULT_MODELS_REGISTRY");
    expect(content).toContain("'claude': 'claude-sonnet-4-6'");
    expect(content).toContain("'codex': 'codex-gpt-5-codex'");
  });

  it('does not include providers with no models', () => {
    const content = buildRegistryContent([], {}, FIXED_TIMESTAMP);
    // Empty maps should still be valid TS
    expect(content).toContain('export const PROVIDER_MODEL_MAP');
  });
});

// ---------------------------------------------------------------------------
// buildCapabilitiesContent — model-capabilities.gen.ts
// ---------------------------------------------------------------------------

describe('buildCapabilitiesContent', () => {
  it('matches snapshot', () => {
    const content = buildCapabilitiesContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toMatchSnapshot();
  });

  it('includes @generated header comment', () => {
    const content = buildCapabilitiesContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain('// @generated by sync-models');
  });

  it('exports REASONING_CAPABLE_MODEL_IDS Set', () => {
    const content = buildCapabilitiesContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain('export const REASONING_CAPABLE_MODEL_IDS = new Set<string>');
    // codex-gpt-5-codex is reasoningCapable: true
    expect(content).toContain("'codex-gpt-5-codex'");
  });

  it('excludes non-reasoning models from reasoning set', () => {
    const content = buildCapabilitiesContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    // claude-sonnet-4-6 is reasoningCapable: false
    // It should NOT appear in REASONING_CAPABLE_MODEL_IDS
    const reasoningSection = content.split('VISION_CAPABLE')[0];
    expect(reasoningSection).not.toContain("'claude-sonnet-4-6'");
  });

  it('exports VISION_CAPABLE_MODEL_IDS Set', () => {
    const content = buildCapabilitiesContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain('export const VISION_CAPABLE_MODEL_IDS = new Set<string>');
    expect(content).toContain("'claude-sonnet-4-6'");
  });

  it('exports THINKING_CAPABLE_MODEL_IDS Set', () => {
    const content = buildCapabilitiesContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain('export const THINKING_CAPABLE_MODEL_IDS = new Set<string>');
    expect(content).toContain("'claude-sonnet-4-6'");
    expect(content).toContain("'gemini-2.5-flash'");
  });

  it('exports MODEL_CONTEXT_WINDOWS for models with contextWindow', () => {
    const content = buildCapabilitiesContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain("'claude-sonnet-4-6': 200000");
    expect(content).toContain("'gemini-2.5-flash': 1000000");
  });

  it('exports MODEL_MAX_OUTPUT_TOKENS for models with maxOutputTokens', () => {
    const content = buildCapabilitiesContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain("'gemini-2.5-flash': 8192");
  });
});

// ---------------------------------------------------------------------------
// buildDisplayContent — model-display.gen.ts
// ---------------------------------------------------------------------------

describe('buildDisplayContent', () => {
  it('matches snapshot', () => {
    const content = buildDisplayContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toMatchSnapshot();
  });

  it('includes @generated header comment', () => {
    const content = buildDisplayContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain('// @generated by sync-models');
  });

  it('exports MODEL_DISPLAY_NAMES record', () => {
    const content = buildDisplayContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain('export const MODEL_DISPLAY_NAMES');
    expect(content).toContain("'claude-sonnet-4-6': 'Claude Sonnet 4.6'");
    expect(content).toContain("'codex-gpt-5-codex': 'GPT-5-Codex'");
    expect(content).toContain("'gemini-2.5-flash': 'Gemini 2.5 Flash'");
  });

  it('exports getRegistryModelDisplayName function', () => {
    const content = buildDisplayContent(FIXTURE_MODELS, FIXED_TIMESTAMP);
    expect(content).toContain('export function getRegistryModelDisplayName');
    expect(content).toContain('return MODEL_DISPLAY_NAMES[modelId]');
  });

  it('escapes single quotes in display names', () => {
    const modelWithApostrophe: ModelEntry[] = [
      { id: 'test-model', name: "Developer's Model", provider: 'test' },
    ];
    const content = buildDisplayContent(modelWithApostrophe, FIXED_TIMESTAMP);
    // Should escape the apostrophe
    expect(content).toContain("\\'");
  });

  it('contains all model IDs from input', () => {
    const content = buildDisplayContent(FIXTURE_MODELS, FIXED_TIMESTAMP);

    for (const model of FIXTURE_MODELS) {
      expect(content).toContain(model.id);
    }
  });
});
